# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_DEB "OFF")
set(CPACK_BINARY_FREEBSD "OFF")
set(CPACK_BINARY_IFW "OFF")
set(CPACK_BINARY_NSIS "OFF")
set(CPACK_BINARY_RPM "OFF")
set(CPACK_BINARY_STGZ "ON")
set(CPACK_BINARY_TBZ2 "OFF")
set(CPACK_BINARY_TGZ "ON")
set(CPACK_BINARY_TXZ "OFF")
set(CPACK_BINARY_TZ "ON")
set(CPACK_BUILD_SOURCE_DIRS "/home/ardakilic/Desktop/CSE396/GUI/scara_gui;/home/ardakilic/Desktop/CSE396/GUI/scara_gui")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libc6, libstdc++6, libgcc-s1")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Arda Kilic k.kilic2019@gtu.edu.tr")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.22/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "scara_gui built using CMake")
set(CPACK_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_INSTALLED_DIRECTORIES "/home/ardakilic/Desktop/CSE396/GUI/scara_gui;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "/tmp/mp-application")
set(CPACK_MODULE_PATH "/usr/lib/x86_64-linux-gnu/cmake/Qt6;/usr/lib/x86_64-linux-gnu/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/usr/lib/x86_64-linux-gnu/cmake/Qt6/3rdparty/kwin;/home/ardakilic/Qt/6.6.1/gcc_64/lib/cmake/Qt6;/home/ardakilic/Qt/6.6.1/gcc_64/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/home/ardakilic/Qt/6.6.1/gcc_64/lib/cmake/Qt6/3rdparty/kwin;/home/ardakilic/Qt/6.6.1/gcc_64/lib/cmake/Qt6;/home/ardakilic/Qt/6.6.1/gcc_64/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/home/ardakilic/Qt/6.6.1/gcc_64/lib/cmake/Qt6/3rdparty/kwin;/home/ardakilic/Qt/6.6.1/gcc_64/lib/cmake/Qt6;/home/ardakilic/Qt/6.6.1/gcc_64/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/home/ardakilic/Qt/6.6.1/gcc_64/lib/cmake/Qt6/3rdparty/kwin;/home/ardakilic/Qt/6.6.1/gcc_64/lib/cmake/Qt6;/home/ardakilic/Qt/6.6.1/gcc_64/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/home/ardakilic/Qt/6.6.1/gcc_64/lib/cmake/Qt6/3rdparty/kwin")
set(CPACK_NSIS_DISPLAY_NAME "scara_gui")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "\$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "scara_gui")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OUTPUT_CONFIG_FILE "/home/ardakilic/Desktop/CSE396/GUI/scara_gui/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.22/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Painter and Gamer Robot")
set(CPACK_PACKAGE_FILE_NAME "scara_gui-0.1-Source")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "scara_gui")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "scara_gui")
set(CPACK_PACKAGE_NAME "scara_gui")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "DrawnPlayBuddy")
set(CPACK_PACKAGE_VERSION "0.1")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "1")
set(CPACK_PACKAGING_INSTALL_PREFIX "/opt/scaragui")
set(CPACK_RESOURCE_FILE_LICENSE "/usr/share/cmake-3.22/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "/usr/share/cmake-3.22/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-3.22/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/home/ardakilic/Desktop/CSE396/GUI/scara_gui;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/ardakilic/Desktop/CSE396/GUI/scara_gui/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "scara_gui-0.1-Source")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TOPLEVEL_TAG "Linux-Source")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux-Source")
set(CPACK_VERBATIM_VARIABLES "ON")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/ardakilic/Desktop/CSE396/GUI/scara_gui/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
